### ISSUE TITLE
Cocos2dCore doesn't build

### ISSUE THREAD

**Issue by djvoracious** [soomla/soomla-cocos2dx-core#7]
Hi guys, Ive just cloned it and Im trying to build it in XCode but it fails. It comes up with cocos2d/extensions/soomla-cocos2dx-core/Soomla/NativeImpl/CCNativeCoreBridge.cpp:33:10: fatal error: 'CCCoreBridgeBinderIos.h' file not found
#include "CCCoreBridgeBinderIos.h"

I downloaded the prebaked zip but that one works.

**Comment by refaelos** [comment]
Fixed on master. Sorry about that.

**Comment by djvoracious** [comment]
Great. I'm going to try and get it working tomorrow 👍
